/*
 * File: app/view/presentation/PresentationViewPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Test.view.presentation.PresentationViewPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.presentationviewpanel',

    requires: [
        'Test.view.presentation.PresentationViewPanelViewModel',
        'Test.view.presentation.PresentationViewPanelViewController',
        'Test.view.presentation.Toolbar',
        'Test.view.presentation.View',
        'Ext.toolbar.Toolbar',
        'Ext.view.View'
    ],

    controller: 'presentationpresentationviewpanel',
    viewModel: {
        type: 'presentationpresentationviewpanel'
    },
    padding: 8,
    scrollable: true,
    layout: 'fit',

    dockedItems: [
        {
            xtype: 'presentationtoolbar',
            reference: 'filters',
            dock: 'top'
        }
    ],
    items: [
        {
            xtype: 'presentationview',
            bind: {
                store: '{presentations}'
            }
        }
    ]

});