/*
 * File: app/view/presentation/PresentationViewPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Test.view.presentation.PresentationViewPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.presentationpresentationviewpanel',

    onStoreLoad: function(store, records, successful, eOpts) {
        Ext.Array.forEach(records, function(presentation){
            presentation.set('favorite', !!Test.stateProvider.get(presentation.id));
        });
    },

    onStoreUpdate: function(store, record, operation, modifiedFieldNames, details, eOpts) {
        console.log('onStoreUpdate');
        console.log(record.data.favorite);
        Test.stateProvider.set(record.id, record.data.favorite);
    }

});
