/*
 * File: app/view/presentation/Toolbar.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Test.view.presentation.Toolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.presentationtoolbar',

    requires: [
        'Test.view.presentation.ToolbarViewModel',
        'Test.view.override.presentation.Toolbar',
        'Ext.plugin.Responsive',
        'Ext.button.Button',
        'Ext.button.Segmented',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'presentationtoolbar'
    },
    viewModel: null,
    responsiveConfig: {
        tall: {
            tall: true
        },
        wide: {
            tall: false
        }
    },
    defaults: {
        margin: 6,
        padding: 2
    },

    layout: {
        type: 'hbox',
        padding: 2
    },
    items: [
        {
            xtype: 'button',
            toggleHandler: function(button, state) {
                button.setGlyph(state?'72@senchacon':'104@senchacon');
            },
            reference: 'favorites',
            cls: 'favorites',
            itemId: 'favorites',
            enableToggle: true,
            glyph: '104@senchacon',
            iconCls: 'heart'
        },
        {
            xtype: 'segmentedbutton',
            reference: 'dayOfWeek',
            itemId: 'dayOfWeek',
            items: [
                {
                    itemId: 'tuesday',
                    enableToggle: true,
                    glyph: '83@senchacon',
                    text: 'Tuesday',
                    value: 2
                },
                {
                    itemId: 'wednesday',
                    glyph: '83@senchacon',
                    text: 'Wednesday',
                    value: 3
                },
                {
                    itemId: 'thursday',
                    glyph: '83@senchacon',
                    text: 'Thursday',
                    value: 4
                }
            ]
        },
        {
            xtype: 'segmentedbutton',
            itemId: 'track',
            allowMultiple: true,
            items: [
                {
                    reference: 'design',
                    cls: 'design',
                    itemId: 'design',
                    enableToggle: true,
                    glyph: '101@senchacon',
                    pressed: true,
                    text: 'Design'
                },
                {
                    reference: 'develop',
                    cls: 'develop',
                    itemId: 'develop',
                    enableToggle: true,
                    glyph: '99@senchacon',
                    pressed: true,
                    text: 'Develop'
                },
                {
                    reference: 'deploy',
                    cls: 'deploy',
                    itemId: 'deploy',
                    enableToggle: true,
                    glyph: '67@senchacon',
                    pressed: true,
                    text: 'Deploy'
                }
            ]
        },
        {
            xtype: 'textfield',
            reference: 'searchTerm',
            itemId: 'search',
            fieldLabel: 'Search',
            labelWidth: 50
        }
    ],
    plugins: [
        {
            ptype: 'responsive'
        }
    ],

    updateTall: function(tall) {
        this.refreshTall();
    },

    refreshTall: function() {
        var tall = !!this.getTall();
        this.down('#search').setVisible(!tall);
        if (tall){

            this.down('#tuesday').setText('7th');
            this.down('#wednesday').setText('8th');
            this.down('#thursday').setText('9th');

            this.down('#design').setText('');
            this.down('#develop').setText('');
            this.down('#deploy').setText('');

        } else {

            this.down('#tuesday').setText('Tuesday');
            this.down('#wednesday').setText('Wednesday');
            this.down('#thursday').setText('Thursday');

            this.down('#design').setText('Design');
            this.down('#develop').setText('Develop');
            this.down('#deploy').setText('Deploy');

        }
    },

    initComponent: function() {
        this.callParent();
        this.refreshTall();
    }

});